spring:
  application:
    name: feign-consumer
  main:
    allow-bean-definition-overriding: true
server:
  port: 9001
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/