spring:
  application:
    name: turbine
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: localhost
server:
  port: 8989
management:
  server:
    port: 8990
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/